catalog:
  '@biomejs/biome': ^2.3.7
  '@chromatic-com/storybook': ^4.1.3
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@playwright/test': ^1.56.1
  '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
  '@storybook/addon-a11y': ^10.0.8
  '@storybook/addon-designs': ^11.0.1
  '@storybook/addon-docs': ^10.0.8
  '@storybook/addon-mcp': ^0.1.4
  '@storybook/addon-themes': ^10.0.8
  '@storybook/addon-vitest': ^10.0.8
  '@storybook/mdx2-csf': ^1.1.0
  '@storybook/test-runner': ^0.24.1
  chromatic: ^13.3.4
  msw-storybook-addon: ^2.0.6
  playwright: ^1.56.1
  remark: ^15.0.1
  remark-cli: ^12.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-lint: ^10.0.1
  remark-preset-lint-consistent: ^6.0.1
  remark-preset-lint-recommended: ^7.0.1
  remark-toc: ^9.0.0
  secretlint: ^11.2.5
  storybook: ^10.0.8
  typescript: ^5.9.3

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
